books= [
    {
        "id": 1,
        "title": "Python Foundations",
        "author": "Anita Rao",
        "publisher": "CodePress",
        "published_date": "2023-04-12",
        "page_count": 384,
        "language": "en",
    },
    {
        "id": 2,
        "title": "FastAPI in Action",
        "author": "S. Kannan",
        "publisher": "DevPath",
        "published_date": "2024-09-01",
        "page_count": 256,
        "language": "en",
    },
    {
        "id": 3,
        "title": "Data Testing with Python",
        "author": "Pushpa J.",
        "publisher": "QAWorks",
        "published_date": "2022-11-30",
        "page_count": 310,
        "language": "en",
    },
    {
        "id": 4,
        "title": "Django & MySQL Made Simple",
        "author": "R. Murugan",
        "publisher": "Tamil Tech Books",
        "published_date": "2021-06-20",
        "page_count": 428,
        "language": "ta",
    },
    {
        "id": 5,
        "title": "ETL Pipelines with PySpark",
        "author": "Neha Gupta",
        "publisher": "DataCraft",
        "published_date": "2024-01-15",
        "page_count": 512,
        "language": "en",
    },
]    